Release HW4; restructure ws to support projects; remove external language support

diff --git a/scripts/bash/build_and_run.sh.in b/scripts/bash/build_and_run.sh.in
--- a/scripts/bash/build_and_run.sh.in
+++ b/scripts/bash/build_and_run.sh.in
@@ -1,7 +1,23 @@
 #! /bin/bash
 
-while [[ $# -gt 0 ]]; do 
-    case "$1" in 
+# Make sure executable tag is passed
+if [[ $# == 0 ]]; then
+    cd ws
+    options=$(find . -maxdepth 1 -mindepth 1 -type d)
+    echo "Must pass executable tag (bash build_and_run.sh <tag>). Here are the your tag options:"
+    while IFS= read -r dir; do
+        dir_name=$(basename "$dir")
+        echo " - $dir_name"
+    done <<< "$options"
+    exit 1
+fi
+
+executable="main-$1"
+
+shift
+
+for arg in "$@"; do
+    case "$arg" in 
         -r|--rebuild)
             echo "Rebuilding from scratch..."
             rm -rf build            
@@ -9,8 +25,17 @@ while [[ $# -gt 0 ]]; do
             rm .env.sh
             shift 1
             ;;
+        -d|--valgrind)
+            echo "Running valgrind on your executable"
+            if command -v valgrind >/dev/null 2>&1; then
+                use_valgrind=true
+            else
+                echo "Valgrind not installed, cannot use --valgrind (-d) debug flag"
+            fi
+            shift 1
+            ;;
         *)
-            echo "Unknown arg '$1'"
+            echo "Unknown arg '$arg'"
             exit 1
             ;;
     esac
@@ -27,7 +52,11 @@ make
 if [ $? == 0 ]; then
     clear
     cd bin
-    ./main 
+    if [ use_valgrind ]; then
+        valgrind ./"$executable"
+    else
+        ./"$executable"
+    fi
 else
     echo "Build Failed!"
 fi
